Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: ruby2.7
      Timeout: 180
      Handler: 'cloudtrail/handler.handler'
      Environment:
        Variables:
          TABLE_NAME: !Ref SimpleTable
      CodeUri: ../lib/cfn-leaprog
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SimpleTable
      Events:
        CloudTrailEvent:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: cfn-leaprog
            FilterPattern: '{$.userIdentity.type = AssumedRole}'
  SimpleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: cfn-leaprog-events
      PrimaryKey:
        Name: RoleArn
        Type: String
      SSESpecification:
        SSEEnabled: true

